---

- name: "Create ns"
  hosts: localhost
  connection: local
  vars:
    namespace_name: "{{ external_dns_namespace }}"
  roles:
    - namespaces

- name:  "Deploy external-dns"
  hosts: localhost
  vars:
    item_name: "{{ external_dns_item_name }}"
    item_namespace: "{{ external_dns_namespace }}"
    item_release_name: "{{ external_dns_release_name }}"
    item_helm_repo: "{{external_dns_helm_repo}}"
    item_helm_repo_endpoint: "{{external_dns_helm_repo_endpoint}}"
    item_chart_version: "{{external_dns_chart_version}}"
  roles:
    - helm_install_item
